all:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
  children:
    db:
      hosts:
        192.168.51.10:
    app:
      hosts:
        192.168.51.100:
      vars:
        ansible_ssh_user: vagrant
        ansible_ssh_pass: vagrant
