IMAGE_NAME = "bento/ubuntu-18.04"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
      
    config.vm.define "app" do |config|
        config.vm.box = IMAGE_NAME
        config.vm.network "private_network", ip: "192.168.51.10"
        config.vm.hostname = "app"
        config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
        # master.vm.provision "ansible" do |ansible|
        #     ansible.playbook = "playbook.yml"
        # end
    end

    config.vm.define "db" do |config|
        config.vm.box = IMAGE_NAME
        config.vm.network "private_network", ip: "192.168.51.100"
        config.vm.hostname = "db"
        config.vm.network :forwarded_port, guest: 22, host: 1234
        config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
        # config.vm.provision "ansible" do |ansible|
        #     ansible.playbook = "nfs-playbook.yml"
        # end
    end

end
